### ISSUE TITLE
Got ERR  Socket #21 SSL BIO error: 

### ISSUE THREAD

**Issue by whlsxl** [tiredofit/docker-libreoffice-online#3]
Hey Tiredofit,

I use traefik as reverse proxy, my `docker-compose.yml` like this.

```
  collabora:
    image: tiredofit/libreoffice-online
    container_name: nextcloud_collabora
    # expose:
    #   - 9980
    cap_add:
      - MKNOD
    environment:
      - ADMIN_USER=[admin]
      - ADMIN_PASS=[password]
      - ALLOWED_HOSTS=*
      - DICTIONARIES="en_GB en_US"
      - LOG_LEVEL=warning
    labels:
      - "traefik.enable=true"
      - "traefik.backend=collabora"
      - "traefik.port=9980"
      - "traefik.frontend.rule=Host:[collabora_URL]"
      - "traefik.docker.network=traefik"
      - "traefik.protocol=https"
    restart: always
    networks:
      - default
      - traefik
```

But when I open collabora_URL, got this error

> wsd-00061-00841 2019-07-06 16:28:05.015766 [ websrv_poll ] ERR  Socket #21 SSL BIO error: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate (0: Success)| ./net/SslSocket.hpp:281
> wsd-00061-00841 2019-07-06 16:28:05.015819 [ websrv_poll ] ERR  Error while handling poll for socket #21 in websrv_poll: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate| ./net/Socket.hpp:570

I do some research, maybe this because need to set `extra_params=--disable-ssl"`, how can I set this `env` ?

**Comment by whlsxl** [comment]
just add env is OK,

```
  collabora:
    image: tiredofit/libreoffice-online
    container_name: nextcloud_collabora
    # expose:
    #   - 9980
    cap_add:
      - MKNOD
    environment:
      - ADMIN_USER=[admin]
      - ADMIN_PASS=[password]
      - ALLOWED_HOSTS=*
      - DICTIONARIES="en_GB en_US"
      - LOG_LEVEL=warning
      - "DONT_GEN_SSL_CERT=true"
      - "extra_params=--o:ssl.enable=false"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=collabora"
      - "traefik.port=9980"
      - "traefik.frontend.rule=Host:[collabora_URL]"
      - "traefik.docker.network=traefik"
      - "traefik.protocol=https"
    restart: always
    networks:
      - default
      - traefik
```
